sudo: false
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

services:
  - mysql

addons:
  apt:
    packages:
    - wget
    - unzip
    - sed

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - ./tests/setup.sh
  - composer install --no-interaction
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

script: vendor/bin/kahlan --coverage=4 --config=./tests/kahlan-config.php
