sudo: false
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

services:
  - mysql

addons:
  apt:
    packages:
    - wget
    - unzip
    - sed

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --no-interaction
  - "echo '' >> conveyor.yml"
  - "cat .travis.db.yml >> conveyor.yml"

script: vendor/bin/conveyor -vvv
